 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/custom_trips", type: :request do
  
  # CustomTrip. As you add validations to CustomTrip, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      CustomTrip.create! valid_attributes
      get custom_trips_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      custom_trip = CustomTrip.create! valid_attributes
      get custom_trip_url(custom_trip)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_custom_trip_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      custom_trip = CustomTrip.create! valid_attributes
      get edit_custom_trip_url(custom_trip)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new CustomTrip" do
        expect {
          post custom_trips_url, params: { custom_trip: valid_attributes }
        }.to change(CustomTrip, :count).by(1)
      end

      it "redirects to the created custom_trip" do
        post custom_trips_url, params: { custom_trip: valid_attributes }
        expect(response).to redirect_to(custom_trip_url(CustomTrip.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new CustomTrip" do
        expect {
          post custom_trips_url, params: { custom_trip: invalid_attributes }
        }.to change(CustomTrip, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post custom_trips_url, params: { custom_trip: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested custom_trip" do
        custom_trip = CustomTrip.create! valid_attributes
        patch custom_trip_url(custom_trip), params: { custom_trip: new_attributes }
        custom_trip.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the custom_trip" do
        custom_trip = CustomTrip.create! valid_attributes
        patch custom_trip_url(custom_trip), params: { custom_trip: new_attributes }
        custom_trip.reload
        expect(response).to redirect_to(custom_trip_url(custom_trip))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        custom_trip = CustomTrip.create! valid_attributes
        patch custom_trip_url(custom_trip), params: { custom_trip: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested custom_trip" do
      custom_trip = CustomTrip.create! valid_attributes
      expect {
        delete custom_trip_url(custom_trip)
      }.to change(CustomTrip, :count).by(-1)
    end

    it "redirects to the custom_trips list" do
      custom_trip = CustomTrip.create! valid_attributes
      delete custom_trip_url(custom_trip)
      expect(response).to redirect_to(custom_trips_url)
    end
  end
end
