 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/user_testimonials", type: :request do
  
  # UserTestimonial. As you add validations to UserTestimonial, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      UserTestimonial.create! valid_attributes
      get user_testimonials_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      user_testimonial = UserTestimonial.create! valid_attributes
      get user_testimonial_url(user_testimonial)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_user_testimonial_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      user_testimonial = UserTestimonial.create! valid_attributes
      get edit_user_testimonial_url(user_testimonial)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new UserTestimonial" do
        expect {
          post user_testimonials_url, params: { user_testimonial: valid_attributes }
        }.to change(UserTestimonial, :count).by(1)
      end

      it "redirects to the created user_testimonial" do
        post user_testimonials_url, params: { user_testimonial: valid_attributes }
        expect(response).to redirect_to(user_testimonial_url(UserTestimonial.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new UserTestimonial" do
        expect {
          post user_testimonials_url, params: { user_testimonial: invalid_attributes }
        }.to change(UserTestimonial, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post user_testimonials_url, params: { user_testimonial: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested user_testimonial" do
        user_testimonial = UserTestimonial.create! valid_attributes
        patch user_testimonial_url(user_testimonial), params: { user_testimonial: new_attributes }
        user_testimonial.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the user_testimonial" do
        user_testimonial = UserTestimonial.create! valid_attributes
        patch user_testimonial_url(user_testimonial), params: { user_testimonial: new_attributes }
        user_testimonial.reload
        expect(response).to redirect_to(user_testimonial_url(user_testimonial))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        user_testimonial = UserTestimonial.create! valid_attributes
        patch user_testimonial_url(user_testimonial), params: { user_testimonial: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested user_testimonial" do
      user_testimonial = UserTestimonial.create! valid_attributes
      expect {
        delete user_testimonial_url(user_testimonial)
      }.to change(UserTestimonial, :count).by(-1)
    end

    it "redirects to the user_testimonials list" do
      user_testimonial = UserTestimonial.create! valid_attributes
      delete user_testimonial_url(user_testimonial)
      expect(response).to redirect_to(user_testimonials_url)
    end
  end
end
